### ISSUE TITLE
SPFx-Promoted-Links not working in IE11

### ISSUE THREAD

**Issue by schneika** [Constellation-Solutions/spfx-promoted-links#1]
SPFx-Promoted-Links WebPart not working in IE11, only in Firefox or Chrome.

In IE11 i allways get the Errors in F12 Debug Console:
 
 `DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
Promoted Links SPFx WebPart not working --(.aspx
HTML1300: Navigation wurde ausgeführt.
Promoted Links SPFx WebPart not working --(.aspx
whoops, illegal rule inserted @-webkit-keyframes animation_16bh5sq{from{opacity:0;}to{opacity:1;}}
The Button component has been deprecated. Use specific variants instead. (PrimaryButton, DefaultButton, IconButton, CommandButton, etc.)`

`The Button component has been deprecated. Use specific variants instead. (PrimaryButton, DefaultButton, IconButton, CommandButton, etc.)`

**Comment by Travis-Constellation** [comment]
IE issues have been resolved.
